Refactoring tf modules and add google example
cloudogu/k8s-ecosystem pull request #76
Opened 2024-06-07 12:57 UTC by nhinze23

Resolves #75

2024-06-10 14:19 UTC, robertauer requested changes

2024-06-10 14:19 UTC, robertauer commented on terraform/examples/ces_google_gke/README.md
> +Create remaining resources
```suggestion
Create the remaining resources, including the CES setup
```

2024-06-10 14:19 UTC, robertauer commented on terraform/examples/ces_google_gke/README.md
> +- `gcloud container clusters get-credentials <cluster_name> --zone europe-west3-c --project $PROJECT_ID`
Doesn't the kubeconfig_generator module generate the kubeconfig?

2024-06-10 14:19 UTC, robertauer commented on terraform/examples/ces_google_gke/README.md
> +### If you plan to use backup & restore with a google bucket firstly you need to create a separate service account.
```suggestion
### If you plan to use backup & restore with a google bucket, you need to create a separate service account first.
```

2024-06-10 14:19 UTC, robertauer commented on terraform/examples/ces_google_gke/README.md
> +# General configuration (not mandatory)
```suggestion
# General configuration
Use the `vars.tfvars.template` file to create `vars.tfvars` and set your GCP project and cluster name in it.
```

2024-06-10 14:19 UTC, robertauer commented on terraform/google_cloud_storage_bucket/main.tf
> +#}
Write a comment how this is maybe useful or delete it.

2024-06-10 14:19 UTC, robertauer commented on terraform/kubeconfig_generator/README.md
> +## setup with GCloud
```suggestion
## Setup with GCloud
```

2024-06-10 14:19 UTC, robertauer commented on terraform/kubeconfig_generator/README.md
> +## setup with Azure
```suggestion
## Setup with Azure
```

2024-06-10 14:19 UTC, robertauer commented on terraform/kubeconfig_generator/README.md
> +Notice that azure has its own way to get the kubeconfig via `azurerm_kubernetes_cluster.aks.kube_config_raw`.
```suggestion
Notice that Azure has its own way to get the kubeconfig via `azurerm_kubernetes_cluster.aks.kube_config_raw`.
```

2024-06-10 14:19 UTC, robertauer commented on terraform/kubeconfig_generator/README.md
> +## get kubeconfig
```suggestion
## Get kubeconfig
```

2024-06-11 05:59 UTC, nhinze23 commented on terraform/azure_aks/README.md
> +  - `az login --scope https://graph.microsoft.com//.default`
No this is correct.. :laughing: 
Try to create a service account without login:
- `az ad sp create-for-rbac --skip-assignment`
and this message will appear:
`Interactive authentication is needed. Please run:
az login --scope https://graph.microsoft.com//.default
`

2024-06-11 06:13 UTC, robertauer approved these changes

2024-06-11 06:15 UTC, merged